### ISSUE TITLE
How can i execute the source code

### ISSUE THREAD

**Issue by george-luofz** [jmrozanec/pdf-converter#1]
I want to convert a pdf file to epub file, so i can read it on my iPhone 掌阅 app, copying some contents sometimes when reading. 
   I feel so exited when find this project. but i failed exactly after i had tried my best to solve millions of java exceptions. by the way, i am a iOS engineer, not familiar with the java language. If you can show me an example to excute it. Thanks so much!

**Comment by jmrozanec** [comment]
@george-luofz sure! Will upload one during this day and come back with it. Best!

**Comment by george-luofz** [comment]
It's very kind of you!

**Comment by jmrozanec** [comment]
@george-luofz you will find a working example at [this repo](https://github.com/jmrozanec/pdf-converter-examples) Please, let us know any inconvenient. Best!
