### ISSUE TITLE
width and height is px or mm?

### ISSUE THREAD

**Issue by Swordce** [jmrozanec/pdf-converter#2]
CodecPage page = decodeService.getPage(i);
RectF rectF = new RectF(0, 0, 1, 1);
int width = (int) page.getWidth();
int height = (int) page.getHeight();

**Comment by jmrozanec** [comment]
@Swordce it should correspond to pixels. Please check with the [corresponding project](https://github.com/JoanZapata/android-pdfview/) for [CodecPage](https://github.com/JoanZapata/android-pdfview/blob/master/android-pdfview/src/main/java/org/vudroid/core/codec/CodecPage.java). Thanks!
