### ISSUE TITLE
pdf-converter

### ISSUE THREAD

**Issue by neusoft-wang** [jmrozanec/pdf-converter#8]
Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: Unable to load library 'gs': Native library (darwin/libgs.dylib) not found in resource path ([file:/Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/lib/charsets.jar

Hello, I've been having this problem for two days. Is there any way to solve it?

**Comment by jmrozanec** [comment]
@neusoft-wang is postscript installed on host machine?

**Comment by neusoft-wang** [comment]
@jmrozanec  I installed Ghostscript. Still, need to install postscript? thx

**Comment by jmrozanec** [comment]
@neusoft-wang did installing Ghostscript fix the issue?
